### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by ARTech-7** [ARTech-7/ARTech-7.github.io#6]
@EmperorDRT1  
I'm pretty sure you have Discord because you starred FKLC/WhatsAppToDiscord. If you do, here's my username and tag.  
alinuxuser#3063  
I recently joined Discord only to hang out with my friends, and I noticed that there's some Linux servers, so that was helpful for me.

**Comment by EmperorDRT1** [comment]
I sent you a friend request on discord. It seems you have disabled direct messages from non-friended users.

**Comment by ARTech-7** [comment]
Yes I did disable non-friend DMs. I accepted the request.
